# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DataVisualizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_visualizerForm(object):
    def setupUi(self, visualizerForm):
        visualizerForm.setObjectName("visualizerForm")
        visualizerForm.resize(1193, 802)
        self.gridLayout = QtWidgets.QGridLayout(visualizerForm)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_2 = CheckableCombobox(visualizerForm)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(visualizerForm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.comboBox = CheckableCombobox(visualizerForm)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(visualizerForm)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(visualizerForm)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 4, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(visualizerForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1169, 743))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 3, 0, 1, 5)

        self.retranslateUi(visualizerForm)
        QtCore.QMetaObject.connectSlotsByName(visualizerForm)

    def retranslateUi(self, visualizerForm):
        _translate = QtCore.QCoreApplication.translate
        visualizerForm.setWindowTitle(_translate("visualizerForm", "Form"))
        self.label.setText(_translate("visualizerForm", "<html><head/><body><p align=\"center\">Select the log</p></body></html>"))
        self.label_2.setText(_translate("visualizerForm", "<html><head/><body><p align=\"center\">Select the log for semi log Axes</p></body></html>"))
        self.pushButton.setText(_translate("visualizerForm", "plot"))
from .checkablecombobox import CheckableCombobox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    visualizerForm = QtWidgets.QWidget()
    ui = Ui_visualizerForm()
    ui.setupUi(visualizerForm)
    visualizerForm.show()
    sys.exit(app.exec_())
