# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DataView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataViewForm(object):
    def setupUi(self, dataViewForm):
        dataViewForm.setObjectName("dataViewForm")
        dataViewForm.resize(1167, 768)
        self.gridLayout = QtWidgets.QGridLayout(dataViewForm)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(dataViewForm)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)

        self.retranslateUi(dataViewForm)
        QtCore.QMetaObject.connectSlotsByName(dataViewForm)

    def retranslateUi(self, dataViewForm):
        _translate = QtCore.QCoreApplication.translate
        dataViewForm.setWindowTitle(_translate("dataViewForm", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dataViewForm = QtWidgets.QWidget()
    ui = Ui_dataViewForm()
    ui.setupUi(dataViewForm)
    dataViewForm.show()
    sys.exit(app.exec_())
